server:
  port: 80

spring:
  profiles:
    active: live

zuul:
  routes:
    jenkins:
      path: /jenkins/**
      url: http://192.168.25.46:38080
      sensitiveHeaders: Cookie,Set-Cookie
    elkindex:
      path: /auth-admin/elk/index/**
      url: http://192.168.25.46:9200/_cat/indices
      sensitiveHeaders: Cookie,Set-Cookie

ribbon:
  eureka:
    enabled: false