spring:
  application:
    name: javaServiceTreeFrameworkAllInOne
  zipkin:
    enabled: true
    service.name: zipkin-service
    sender.type: web
    base-url: http://192.168.25.46:9411
  sleuth:
    enabled: true
    sampler:
      probability: 1.0

tokenUrl: http://313.co.kr:8585/auth/realms/devops/protocol/openid-connect/token
clientId: Java-Service-Tree-Framework-Allinone-Proxy
clientSecret: b54ae045-7777-4f8b-9d52-15f15d84f56b
accessTokenUser: admin
accessTokenPass: qwe123