spring:
  application:
    name: javaServiceTreeFrameworkAllInOne
  zipkin:
    enabled: true
    service.name: zipkin-service
    sender.type: web
    base-url: http://192.168.25.46:9411
  sleuth:
    enabled: true
    sampler:
      probability: 1.0

tokenUrl: http://313.co.kr:8585/auth/realms/master/protocol/openid-connect/token
clientId: javaServiceTreeFrameworkAllInOne
clientSecret: dafd4992-a7f6-4e8f-b809-b2bafad04fa8
accessTokenUser: integrationuser
accessTokenPass: qwe123